module.exports = {
  asset: require('./asset/asset.json'),
  pc: require('./asset/pc.json'),
  car: require('./asset/car.json'),
  project: require('./project.json'),
  party: require('./party/party.json'),
  person: require('./party/person.json'),
  organization: require('./party/organization.json'),
  secret: require('./secret.json'),
  task: require('./task.json'),
  activity: require('./activity/activity.json'),
  timeRecord: require('./activity/timeRecord.json'),
  travelRecord: require('./activity/travelRecord.json'),
  shipment: require('./shipment.json'),
  instance: require('./instance.json'),
  notification: require('./notification.json'),
  user: require('./user.json'),
  file: require('./file.json'),
  article: require('./article.json'),
  address: require('./address.json'),
}